In [2]:
pip install rouge


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: /Users/michaloleszak/Documents/playground/.playground/bin/python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
from rouge import Rouge 

hypothesis = "Anna searches for her favorite book 'The Silent Stars', and Ben admits he borrowed it without asking, leading to a plan to discuss it later"

reference = "Anna realizes Ben borrowed her favorite book without asking, and they agree to discuss it once he's finished reading"

rouge = Rouge()
scores = rouge.get_scores(hypothesis, reference)
scores

[{'rouge-1': {'r': 0.631578947368421,
   'p': 0.5217391304347826,
   'f': 0.571428566473923},
  'rouge-2': {'r': 0.2777777777777778,
   'p': 0.20833333333333334,
   'f': 0.23809523319727902},
  'rouge-l': {'r': 0.47368421052631576,
   'p': 0.391304347826087,
   'f': 0.42857142361678}}]

In [3]:
5/0.2777777777777778

18.0

In [4]:
def generate_bigrams(sentence):
    """Generate bigrams from a sentence."""
    tokens = sentence.split()
    bigrams = [(tokens[i], tokens[i+1]) for i in range(len(tokens)-1)]
    return set(bigrams)

def count_bigram_matches(sentence1, sentence2):
    """Count the number of bigram matches between two sentences."""
    bigrams1 = generate_bigrams(sentence1)
    bigrams2 = generate_bigrams(sentence2)
    
    matching_bigrams = bigrams1.intersection(bigrams2)
    print(matching_bigrams)
    return len(matching_bigrams)

# Example
hypothesis = "Anna searches for her favorite book 'The Silent Stars', and Ben admits he borrowed it without asking, leading to a plan to discuss it later"
reference = "Anna realizes Ben borrowed her favorite book without asking, and they agree to discuss it once he's finished reading"

print(count_bigram_matches(hypothesis, reference))  # Output: 3


{('her', 'favorite'), ('discuss', 'it'), ('favorite', 'book'), ('to', 'discuss'), ('without', 'asking,')}
5


In [31]:
from rouge import Rouge 

hypothesis = "climate change is a significant threat to global biodiversity"

reference = "climate change is not a significant threat to global biodiversity"

rouge = Rouge()
scores = rouge.get_scores(hypothesis, reference)
scores

[{'rouge-1': {'r': 0.9, 'p': 1.0, 'f': 0.9473684160664821},
  'rouge-2': {'r': 0.7777777777777778, 'p': 0.875, 'f': 0.823529406782007},
  'rouge-l': {'r': 0.9, 'p': 1.0, 'f': 0.9473684160664821}}]

In [21]:
2 * (0.63*0.52) / (0.63+0.52)

0.5697391304347826

In [6]:
print(scores[0]["rouge-l"])

{'r': 0.47368421052631576, 'p': 0.391304347826087, 'f': 0.42857142361678}


In [17]:
import numpy as np

def bootstrap_confidence_interval_detailed(data, metric_func, alpha=0.05, n_bootstrap=1000, seed=42):
    """
    Estimate the (1-alpha) confidence interval of a metric using the bootstrap method and return intermediate results.

    Parameters:
    - data (1D array-like): Input data.
    - metric_func (callable): Function to compute the desired metric. It should take an array-like as input and return a scalar.
    - alpha (float): Significance level. If alpha is 0.05, then the function returns the 95% confidence interval.
    - n_bootstrap (int): Number of bootstrap samples to create.
    - seed (int): Random seed for reproducibility.

    Returns:
    - dict: Dictionary with keys:
        - 'bootstrap_samples': 2D array of bootstrap samples.
        - 'bootstrap_metrics': 1D array of metric values computed for each bootstrap sample.
        - 'confidence_interval': tuple with the lower and upper bounds of the confidence interval.
    """
    
    # Set the random seed for reproducibility
    np.random.seed(seed)
    
    # Generate bootstrap samples
    bootstrap_samples = np.random.choice(data, (n_bootstrap, len(data)), replace=True)
    
    # Compute the metric on each bootstrap sample
    bootstrap_metrics = np.apply_along_axis(metric_func, 1, bootstrap_samples)

    # Calculate the lower and upper percentiles for confidence interval
    lower = np.percentile(bootstrap_metrics, 100 * (alpha / 2))
    upper = np.percentile(bootstrap_metrics, 100 * (1 - alpha / 2))
    
    results = {
        'bootstrap_samples': bootstrap_samples,
        'bootstrap_metrics': bootstrap_metrics,
        'confidence_interval': (lower, upper)
    }
    
    return results

# Example usage:
data = np.random.randn(5)  # Generating 100 random data points from a standard normal distribution
results = bootstrap_confidence_interval_detailed(data, np.mean, n_bootstrap=3)
print(f"Bootstrap Samples:\n{results['bootstrap_samples'][:5]}...")  # Print the first 5 bootstrap samples for brevity
print(f"Bootstrap Metrics (Means): {results['bootstrap_metrics'][:5]}...")  # Print the first 5 computed metrics
print(f"Mean 95% Confidence Interval: {results['confidence_interval']}")


Bootstrap Samples:
[[-0.22672246  0.65304831  0.92066672  0.65304831  0.65304831]
 [ 0.10576365  0.92066672  0.92066672  0.92066672  0.65304831]
 [-0.22672246  0.92066672  0.65304831  0.10576365 -0.22672246]]...
Bootstrap Metrics (Means): [0.53061784 0.70416242 0.24520675]...
Mean 95% Confidence Interval: (0.259477306844585, 0.6954851919243095)


In [14]:
!pip3 install nltk


[notice] A new release of pip is available: 23.0.1 -> 23.3.2
[notice] To update, run: python3.11 -m pip install --upgrade pip


In [62]:
import nltk

machine = "Szybki lis skacze nad leniwym psem".split(" ")
golden = "Szybki brązowy lis przeskakuje nad leniwym psem".split(" ")

bleu_score = nltk.translate.bleu_score.sentence_bleu(
    [golden], machine, weights=(1./3., 1./3. , 1./3.)
)

print(bleu_score)

0.36973494931036327


In [64]:
geom_avg_precision = (0.83 * 0.4 * 0.25) ** (1/3)
geom_avg_precision

0.4362070671454838

In [66]:
breviy_penalty = np.exp(1 - len(golden)/len(machine))
breviy_penalty

0.846481724890614

In [67]:
geom_avg_precision * breviy_penalty

0.369241310606785